-- Run these queries in the CLI to create database and table

-- Create queries for todo app client side functions
CREATE DATABASE pernstack;

-- \c into pernstack,

-- Creating the schema of todo table
CREATE TABLE todo(
  todo_id SERIAL PRIMARY KEY, 
  description VARCHAR(255), 
  email VARCHAR(255) NOT NULL DEFAULT 'test@test.com', 
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  isFinished BOOLEAN DEFAULT FALSE
); 

-- NOT NULL means it's required, and can't be empty. 


-- Creating queries for todo app login functions 

-- Need to download 'uuid-ossp' in PostgreSQL for implementing uuid_generate function 
create extension if not exists "uuid-ossp"; 

CREATE TABLE users(
  user_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), 
  user_email VARCHAR(255) NOT NULL, 
  user_password VARCHAR(255) NOT NULL
); 

-- Create a test user in users table, it must be single quotation
-- user_id will be generated by default
INSERT INTO users (user_email, user_password) VALUES ('charlie@gmail.com', 'qaz123'); 

-- Check users table 
SELECT * FROM users;